baseURL = 'http://amf3.github.io/'
languageCode = 'en-us'
title = 'Adam Faris'
publishDir = 'docs'
theme = 'PaperMod'

[[menu.main]]
identifier = "articles"
name = "articles"
url = "/articles/"
weight = 10

[[menu.main]]
identifier = "search"
name = "search"
url = "search/"
weight = 20

[[menu.main]]
identifier = "about"
name = "about"
url = "/about/"
weight = 30

[outputs]
home = [ "HTML", "RSS", "JSON" ]

[params.fuseOpts]
isCaseSensitive = false
shouldSort = true
location = 0
distance = 1_000
threshold = 0.4
minMatchCharLength = 0
keys = [ "title", "permalink", "summary", "content" ]

[params]
ShowBreadCrumbs = false
ShowShareButtons = false