baseURL = 'https://amf3.github.io/'
languageCode = 'en-us'
title = 'Adam Faris'
publishDir = 'docs'
theme = 'PaperMod'
enableRobotsTXT = 'true'

[[menu.main]]
identifier = "articles"
name = "articles"
url = "/articles/"
weight = 20

[[menu.main]]
identifier = "search"
name = "search"
url = "search/"
weight = 10

[[menu.main]]
identifier = "about"
name = "about"
url = "/about/"
weight = 30

[outputs]
home = [ "HTML", "RSS", "JSON" ]
# home =  ["HTML", "RSS", "JSON"]
rss = ['rss']
# page =  ["HTML", "RSS", "JSON"]
# section =  ["HTML", "RSS", "JSON"]
# taxonomy =  ["HTML", "RSS", "JSON"]
# term =  ["HTML", "RSS", "JSON"]

[params]
ShowBreadCrumbs = 'false'
ShowShareButtons = 'true'
ShareButtons = ['rss']
ShowFullTextinRSS = 'true'
mainSections = ['articles']
analytics.google.SiteVerificationTag = '6ZFu-1_Lir3DsFJP8sshXEJ1_SjtFUw9TIISOcaJh7E'
analytics.bing.SiteVerificationTag = 'C1E02AC59FE7ECBDB6D9EFB7D5E02B65'
ShowWordCount = 'true'
env = 'production'
ShowCodeCopyButtons = 'true'

[services.googleAnalytics]
ID = 'G-MKR06D6KGD'

[params.fuseOpts]
isCaseSensitive = false
shouldSort = true
location = 0
distance = 1000
threshold = 0.4
minMatchCharLength = 4
keys = [ "title", "permalink", "summary", "content" ]
  
[[params.socialIcons]]
name = 'rss'
url = 'https://amf3.github.io/index.xml'

[markup.goldmark.renderer]
unsafe = false
