baseURL = 'https://amf3.github.io/'
languageCode = 'en-us'
title = 'Adam Faris'
publishDir = 'docs'
theme = 'PaperMod'
enableRobotsTXT = 'true'

[[menu.main]]
identifier = "articles"
name = "articles"
url = "/articles/"
weight = 20

[[menu.main]]
identifier = "search"
name = "search"
url = "search/"
weight = 10

[[menu.main]]
identifier = "about"
name = "about"
url = "/about/"
weight = 30

[outputs]
home = ['html']
page = ['html']
rss = ['rss']
section = ['html', 'rss']
taxonomy = ['html']
term = ['html']

[params]
env = 'production'
ShowBreadCrumbs = 'false'
ShowShareButtons = 'true'
ShareButtons = ['rss']
ShowFullTextinRSS = 'true'
mainSections = ['articles']

[params.fuseOpts]
isCaseSensitive = false
shouldSort = true
location = 0
distance = 1_000
threshold = 0.4
minMatchCharLength = 0
keys = [ "title", "permalink", "summary", "content" ]
  
[[params.socialIcons]]
name = 'rss'
url = 'https://amf3.github.io/index.xml'

[markup.goldmark.renderer]
unsafe = false