name: "IndexNow"
on:
  workflow_dispatch:

jobs:
  check-and-submit:
    runs-on: ubuntu-latest
    steps:
      - name: Submit_URLs_to_IndexNow
        uses: bojieyang/indexnow-action@v3
        with:
          sitemap-location: 'https://amf3.github.io/sitemap.xml'
          key: '4f640cc711b44fc79cee680c3ed2d5ca'  # This is an ID not a secret key
          key-location: 'https://amf3.github.io/4f640cc711b44fc79cee680c3ed2d5ca.txt'
          since: 9999
          since-unit: day
          lastmod-required: false
